### ISSUE TITLE
The Package-lock.json prevent from installing dependencies

### ISSUE THREAD

**Issue by Killy85** [lauthieb/code-notes#1]
After my first checkout I did try to install all the dependencies by running `npm i` but it resulted in an error because of a hash that has been computed on another computer but that is present in the package-lock.json 

### Expected Behavior
I think that, even if it's a minor problem and that is really easy to do, it may be great if we don't have to remove the package-lock after every pull

### Current Behavior
The package-lock prevent from installing dependencies. We must delete it before to run `npm install`

### Possible Solution
Add package-lock.json to the gitignore

### Steps to Reproduce (for bugs)
1. Checkout the project on another computer
2. Run `npm install`

### Your Environment
* Version used: v1.0.0, last commit : edae19b9aacabe4a4cf32bb4058e191ad512e22b
* Operating System and version: Ubuntu 16.04

**Comment by lauthieb** [comment]
Hello Killy85 !

First, thanks for your contribution.
I understand your problem, it’s my fault. I work on a pro laptop which have some configurations of my company (like the nexus registry if npm packages in this cases...)
Your solution cannot be good because the purpose of package-json.lock is to increase the rapidiity of downloading packages from npm because of theses hashes. So it doesn’t have to figure in .gitignore.
I will fix the problem this aftertoon in publishing a new package-lock.json with the npmjs.org registry.
Thanks a lot !
