### ISSUE TITLE
Delete/Update Note do not work

### ISSUE THREAD

**Issue by MrMoshkovitz** [lauthieb/code-notes#152]
Hi,
I am using code notes two days, suddenly i cannot delete or update existing local notes...
although i am able to create new ones..

Please contact me for help

**Comment by lauthieb** [comment]
Hi @MrMoshkovitz can you please open the DevTools by clicking on:

![image](https://user-images.githubusercontent.com/9600228/90571711-a365af80-e1b2-11ea-97c8-58d5a9895d3f.png)

And see us the console logs.

Thanks

**Comment by MrMoshkovitz** [comment]
![gitSheetCodenotes](https://user-images.githubusercontent.com/50079480/90683092-af16ac00-e26e-11ea-9af2-4729735e0971.png)

**Comment by redkross** [comment]
Bonjour, 

Je rencontre le même problème, impossible de mettre à jour / supprimer un snippet (local ou gist).

![image](https://user-images.githubusercontent.com/6020000/91656814-20026300-eabc-11ea-9ad9-38182109b52d.png)

Cordialement,

**Comment by lauthieb** [comment]
Thanks, I will check asap.

**Comment by wchen928** [comment]
I have the same issue. However, when I run it in development mode, I had no problem deleting it. Do you have any thoughts on why this might be?

**Comment by MrMoshkovitz** [comment]
didnt got no answer Linda...

**Comment by lauthieb** [comment]
Sorry, I don't have any time allowed for the moment with my professional activities :'(

**Comment by undefynd** [comment]
![Bildschirmfoto 2020-10-05 um 17 57 55](https://user-images.githubusercontent.com/68283314/95103401-d8af6800-0734-11eb-939e-f8a05ec95f30.png)
I got the same error.

**Comment by richtrefz** [comment]
Can't delete a snippet - can't even do application -> about
![Screenshot-at-2020-11-18-16-31-38](https://user-images.githubusercontent.com/1500959/99590683-ae033100-29bb-11eb-99b8-8de76b9ec47c.png)

**Comment by genepy** [comment]
**Describe the bug**
It is impossible to delete a snipet via the trash button

**To Reproduce**
Steps to reproduce the behavior:
1. create a new snipet
2. click on the trash button
3. to see the error message => click in the menu on Application => toogle dev tool => console

**Expected behavior**
I expect the snipet to be deleted when I click on the trash button

**Screenshots**
![code-notes_trash button_fail](https://user-images.githubusercontent.com/7634998/159771440-8b297731-b657-4b90-a3ef-e9f34fb88054.png)

**Desktop**
 - OS: Windows 10 Entreprise
 - Version: 21H1
 - code-note version : 1.2.4

**Additional context**
The trash button works on code-note version 1.2.3
