### ISSUE TITLE
Custom languages

### ISSUE THREAD

**Issue by Canyata** [lauthieb/code-notes#16]
I am sysadmin and I would love to use code-notes to store some SQL request or Cisco configuration on it.
Could you add those languages please?

**Comment by lauthieb** [comment]
Hello @Canyata ! Thank you very much for request ;)
I will add SQL support in the next version 1.1.1 (probably tomorrow).
I depend on the "ace editor" to show coloration on editor, I did'nt find a mode for Cisco, so I think you should use "text" mode sorry...

**Comment by Canyata** [comment]
Is that possible to create custom language?
I would like to sort them even if it is displayed in text mode

**Comment by lauthieb** [comment]
Oh okay, it's possible. I have to do some refactoring but it's possible. I will keep your informed ! Thanks for the support ;)

**Comment by Ichigo49** [comment]
Hello @lauthieb !
Great work ! very useful
Is it possible to add some PowerShell support ?

**Comment by Kayoku** [comment]
Hi @lauthieb 
Maybe also C/C++ and Bash would be great, and split Python in "Python" for python2 and "Python3" for python3. Both are very different :)

**Comment by lauthieb** [comment]
Hello all, for the UX, I plan to replace the future languages select box with an input autocomplete. What do you think ?

**Comment by Ichigo49** [comment]
hi !
I like the idea !

**Comment by jzillmann** [comment]
Custom languages would be awesome! Would like to have a flutter/dart one!

**Comment by bantya** [comment]
I agree that the separate language field is required for deciding the correct syntax highlighter and language support for the snippet and it is the easiest way to achieve what you want, but it limits us to predefined languages.

Instead of selecting or auto-completing the language name, you could try to provide a field for filename (filename + file-extension) instead of two separate fields for filename and language. Now, you can deduce the language name through the extension of the snippet provided. This will be easier for most of us, as it will enable them to use the language we want.

**Comment by ricozone** [comment]
Yes would be nice to specify a custom langage name and affect to it an already defined one.
Example: "3dsmax maxscript" afected to "text" color scheme
